import { useMemo, useState } from 'react'
import { Activity, CalendarDays, Check, Clock3, Edit3, FolderKanban, GripVertical, LayoutDashboard, Plus, Save, Trash2, UserCircle2, Users, X } from 'lucide-react'

type Status='todo'|'doing'|'done'
type Role='user'|'manager'
type Person={id:string;name:string;specialty:string;age:number;role:Role}
type Group={id:string;name:string}
type Project={id:string;name:string;start:string;end:string;groupId:string;ownerId:string;description:string}
type Task={id:string;title:string;projectId:string;status:Status;groupId:string;assigneeId:string;createdAt:string;completedAt?:string}
type History={id:string;personId:string;action:string;taskId:string;projectId:string;at:string}

const initialPeople:Person[]=[{id:'p1',name:'احمد سلیمانی',specialty:'توسعه‌دهنده',age:29,role:'manager'},{id:'p2',name:'محمد رضایی',specialty:'برنامه‌نویس',age:27,role:'user'},{id:'p3',name:'سارا احمدی',specialty:'طراح UI/UX',age:26,role:'user'}]
const initialGroups:Group[]=[{id:'g1',name:'توسعه'},{id:'g2',name:'طراحی'},{id:'g3',name:'بازاریابی'}]
const initialProjects:Project[]=[{id:'pr1',name:'وب‌سایت شرکت',start:'2026-09-01',end:'2026-09-24',groupId:'g1',ownerId:'p1',description:'طراحی و توسعه وب‌سایت اصلی شرکت.'},{id:'pr2',name:'اپلیکیشن موبایل',start:'2026-09-10',end:'2026-10-18',groupId:'g1',ownerId:'p2',description:''},{id:'pr3',name:'کمپین پاییزه',start:'2026-09-20',end:'2026-10-08',groupId:'g3',ownerId:'p3',description:''}]
const initialTasks:Task[]=[{id:'t1',title:'طراحی صفحه اصلی',projectId:'pr1',status:'done',groupId:'g2',assigneeId:'p3',createdAt:'2026-09-01',completedAt:'2026-09-05'},{id:'t2',title:'پیاده‌سازی داشبورد',projectId:'pr1',status:'doing',groupId:'g1',assigneeId:'p1',createdAt:'2026-09-04'},{id:'t3',title:'اتصال API',projectId:'pr1',status:'todo',groupId:'g1',assigneeId:'p2',createdAt:'2026-09-08'},{id:'t4',title:'طراحی رابط کاربری',projectId:'pr2',status:'doing',groupId:'g2',assigneeId:'p3',createdAt:'2026-09-10'},{id:'t5',title:'ساخت نسخه اولیه',projectId:'pr2',status:'todo',groupId:'g1',assigneeId:'p2',createdAt:'2026-09-11'},{id:'t6',title:'تقویم محتوایی',projectId:'pr3',status:'todo',groupId:'g3',assigneeId:'p3',createdAt:'2026-09-20'}]
const statusMeta:Record<Status,{title:string;dot:string;weight:number}>={todo:{title:'در انتظار انجام',dot:'bg-slate-400',weight:0},doing:{title:'در حال انجام',dot:'bg-amber-400',weight:50},done:{title:'انجام شده',dot:'bg-emerald-400',weight:100}}
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`
const fmt=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('fa-IR',{month:'short',day:'numeric'})
const calcProgress=(id:string,tasks:Task[])=>{const ts=tasks.filter(t=>t.projectId===id);return ts.length?Math.round(ts.reduce((s,t)=>s+statusMeta[t.status].weight,0)/ts.length):0}

export default function App(){
 const [page,setPage]=useState<'board'|'timeline'|'activity'>('board'),[projects,setProjects]=useState(initialProjects),[tasks,setTasks]=useState(initialTasks),[groups,setGroups]=useState(initialGroups)
 const [people,setPeople]=useState<Person[]>(()=>{try{return JSON.parse(localStorage.getItem('orbit-people')||'null')||initialPeople}catch{return initialPeople}})
 const [currentUserId,setCurrentUserId]=useState(()=>localStorage.getItem('orbit-current-user')||'p1'),[history,setHistory]=useState<History[]>([]),[dragId,setDragId]=useState<string|null>(null)
 const [modal,setModal]=useState<'task'|'project'|'group'|'account'|null>(null),[selectedProject,setSelectedProject]=useState('pr1'),[deleteId,setDeleteId]=useState<string|null>(null),[editId,setEditId]=useState<string|null>(null)
 const personMap=useMemo(()=>Object.fromEntries(people.map(p=>[p.id,p])),[people]),projectMap=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,p])),[projects]),groupMap=useMemo(()=>Object.fromEntries(groups.map(g=>[g.id,g])),[groups])
 const progressMap=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,calcProgress(p.id,tasks)])),[projects,tasks]),overall=projects.length?Math.round(projects.reduce((s,p)=>s+progressMap[p.id],0)/projects.length):0,currentUser=personMap[currentUserId]||people[0]
 const savePeople=(next:Person[])=>{setPeople(next);localStorage.setItem('orbit-people',JSON.stringify(next))}
 const moveTask=(id:string,status:Status)=>{const t=tasks.find(x=>x.id===id);if(!t||t.status===status){setDragId(null);return}setTasks(ts=>ts.map(x=>x.id===id?{...x,status,completedAt:status==='done'?new Date().toISOString().slice(0,10):undefined}:x));setHistory(h=>[{id:uid('h'),personId:currentUser.id,action:`${statusMeta[status].title} شد`,taskId:id,projectId:t.projectId,at:new Date().toISOString()},...h]);setDragId(null)}
 const deleteProject=(id:string)=>{if(currentUser.role!=='manager')return;setProjects(ps=>ps.filter(p=>p.id!==id));setTasks(ts=>ts.filter(t=>t.projectId!==id));setHistory(h=>h.filter(x=>x.projectId!==id));if(selectedProject===id)setSelectedProject(projects.find(p=>p.id!==id)?.id||'');setDeleteId(null)}
 const updateDescription=(id:string,d:string)=>{setProjects(ps=>ps.map(p=>p.id===id?{...p,description:d}:p));setEditId(null)}
 const addProject=(name:string,start:string,end:string,groupId:string,description:string)=>{if(name.trim()){const id=uid('pr');setProjects(ps=>[...ps,{id,name:name.trim(),start,end,groupId,ownerId:currentUser.id,description}]);setSelectedProject(id)}setModal(null)}
 const addTask=(title:string,projectId:string,groupId:string,assigneeId:string)=>{if(title.trim())setTasks(ts=>[...ts,{id:uid('t'),title:title.trim(),projectId,status:'todo',groupId,assigneeId,createdAt:new Date().toISOString().slice(0,10)}]);setModal(null)}
 const register=(name:string,specialty:string,age:number,role:Role)=>{const next=people.map(p=>p.id===currentUserId?{...p,name,specialty,age,role}:p);savePeople(next);setModal(null)}
 return <div dir="rtl" className="min-h-screen bg-[#08090d] text-slate-200 font-sans"><aside className="fixed right-0 top-0 bottom-0 hidden md:flex w-64 flex-col border-l border-white/10 bg-[#0d0f15] p-5"><div className="flex items-center gap-3 mb-8"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 text-xl font-black">O</div><div><b className="text-white">Orbit Tasks</b><p className="text-xs text-slate-500">مدیریت پروژه و تیم</p></div></div><nav className="space-y-2">{([['board','برد پروژه',LayoutDashboard],['timeline','تایم‌لاین',CalendarDays],['activity','فعالیت افراد',Activity]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setPage(id)} className={`w-full flex items-center gap-3 rounded-xl px-4 py-3 text-sm ${page===id?'bg-violet-500/15 text-violet-300':'text-slate-400 hover:bg-white/5'}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-xs text-slate-500">پیشرفت کل پروژه‌ها</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{width:`${overall}%`}}/></div><b className="mt-2 block text-lg">{overall}٪</b></div></aside>
 <main className="md:mr-64 p-5 md:p-8 max-w-[1600px] mx-auto"><header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm text-violet-400">فضای کاری تیم</p><h1 className="mt-1 text-3xl font-black text-white">مدیریت پروژه</h1><p className="mt-1 text-sm text-slate-500">پروژه‌ها، تسک‌ها و اعضای تیم را مدیریت کنید.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>setModal('account')} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 hover:bg-white/[.07]"><UserCircle2 size={28} className="text-violet-300"/><span className="hidden sm:block"><b className="block text-xs text-white">{currentUser?.name}</b><small className="text-[10px] text-slate-500">{currentUser?.role==='manager'?'مدیر':'کاربر'}</small></span></button><button onClick={()=>setModal('group')} className="btn-secondary"><Users size={16}/> گروه جدید</button><button onClick={()=>setModal('task')} className="btn-secondary"><Plus size={16}/> تسک جدید</button><button onClick={()=>setModal('project')} className="btn-primary"><FolderKanban size={16}/> پروژه جدید</button></div></header>
 {page==='board'&&<><section className="mb-6 grid grid-cols-2 lg:grid-cols-4 gap-3">{[['پروژه‌ها',projects.length],['تسک‌ها',tasks.length],['انجام شده',tasks.filter(t=>t.status==='done').length],['میانگین پیشرفت',`${overall}٪`]].map(([l,v])=><div key={l as string} className="rounded-2xl border border-white/10 bg-[#10121a] p-4"><p className="text-xs text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-white">{v}</strong></div>)}</section><section className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-3">{projects.map(p=><ProjectCard key={p.id} project={p} percent={progressMap[p.id]} canDelete={currentUser.role==='manager'} onDelete={()=>setDeleteId(p.id)} onEdit={()=>setEditId(p.id)}/>)}</section><section className="grid grid-cols-1 lg:grid-cols-3 gap-5">{(Object.keys(statusMeta) as Status[]).map(status=><div key={status} onDragOver={e=>e.preventDefault()} onDrop={()=>dragId&&moveTask(dragId,status)} className="min-h-[460px] rounded-2xl border border-white/10 bg-[#0f1118] p-4"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${statusMeta[status].dot}`}/><h2 className="font-bold text-white">{statusMeta[status].title}</h2></div><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-slate-500">{tasks.filter(t=>t.status===status).length}</span></div><div className="space-y-3">{tasks.filter(t=>t.status===status).map(t=><article key={t.id} draggable onDragStart={()=>setDragId(t.id)} className="cursor-grab rounded-xl border border-white/10 bg-[#171923] p-4"><div className="flex gap-2"><GripVertical size={17} className="text-slate-600"/><div className="flex-1"><h3 className="font-semibold text-white">{t.title}</h3><p className="mt-1 text-xs text-slate-500">{projectMap[t.projectId]?.name}</p><div className="mt-3 flex flex-wrap gap-1.5"><span className="chip">{groupMap[t.groupId]?.name}</span><span className="chip">{personMap[t.assigneeId]?.name}</span>{personMap[t.assigneeId]&&<RoleBadge role={personMap[t.assigneeId].role}/>}</div></div></div><div className="mt-3 text-xs text-slate-500">شروع: {fmt(t.createdAt)}</div></article>)}</div></div>)}</section></>}{page==='timeline'&&<Timeline projects={projects} progressMap={progressMap}/>} {page==='activity'&&<ActivityLog history={history} tasks={tasks} projects={projects} people={people}/>}</main>
 {modal==='account'&&<Modal title="حساب کاربری" onClose={()=>setModal(null)}><AccountForm person={currentUser} onSubmit={register}/></Modal>}{modal==='project'&&<Modal title="ساخت پروژه جدید" onClose={()=>setModal(null)}><ProjectForm groups={groups} onSubmit={addProject}/></Modal>}{modal==='task'&&<Modal title="ساخت تسک جدید" onClose={()=>setModal(null)}><TaskForm projects={projects} groups={groups} people={people} selectedProject={selectedProject} onSubmit={addTask}/></Modal>}{modal==='group'&&<Modal title="ساخت گروه جدید" onClose={()=>setModal(null)}><GroupForm onSubmit={name=>{if(name.trim())setGroups(g=>[...g,{id:uid('g'),name:name.trim()}]);setModal(null)}}/></Modal>}{editId&&<Modal title="ویرایش توضیحات پروژه" onClose={()=>setEditId(null)}><DescriptionForm project={projectMap[editId]} onSubmit={d=>updateDescription(editId,d)}/></Modal>}{deleteId&&<Modal title="حذف پروژه" onClose={()=>setDeleteId(null)}><div className="space-y-4"><div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4"><p className="font-semibold text-white">آیا مطمئنی؟</p><p className="mt-2 text-sm text-slate-400">تمام تسک‌ها و فعالیت‌های این پروژه نیز حذف می‌شوند. این عملیات قابل بازگشت نیست.</p></div><div className="flex gap-2"><button onClick={()=>setDeleteId(null)} className="btn-secondary flex-1 justify-center">انصراف</button><button onClick={()=>deleteProject(deleteId)} className="flex-1 rounded-xl bg-red-600 px-4 py-2.5 font-bold text-white">حذف پروژه</button></div></div></Modal>}
 <style>{`.btn-primary,.btn-secondary{display:flex;align-items:center;gap:7px;border-radius:12px;padding:10px 14px;font-size:13px;font-weight:700}.btn-primary{background:#7c3aed;color:white}.btn-secondary{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#cbd5e1}.chip{display:inline-flex;border-radius:999px;background:rgba(255,255,255,.06);padding:4px 8px;font-size:10px;color:#94a3b8}.field{width:100%;border:1px solid rgba(255,255,255,.1);background:#0b0d12;color:#e2e8f0;border-radius:10px;padding:10px;outline:none}.field:focus{border-color:#7c3aed}`}</style></div>}

function ProjectCard({project,percent,canDelete,onDelete,onEdit}:{project:Project;percent:number;canDelete:boolean;onDelete:()=>void;onEdit:()=>void}){return <div className="rounded-2xl border border-white/10 bg-[#10121a] p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="text-xs text-slate-500">پیشرفت پروژه</p><h3 className="mt-1 font-bold text-white">{project.name}</h3></div><div className="flex items-start gap-1"><b className="text-violet-300">{percent}٪</b>{canDelete&&<button title="حذف پروژه" onClick={onDelete} className="rounded-lg p-1 text-slate-600 hover:bg-red-500/10 hover:text-red-400"><Trash2 size={16}/></button>}</div></div><div className="mt-3 h-2 rounded-full bg-white/10 overflow-hidden"><div className="h-full rounded-full bg-violet-500" style={{width:`${percent}%`}}/></div><div className="mt-3 rounded-xl border border-white/5 bg-white/[.02] p-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-400">توضیحات</span><button onClick={onEdit} className="flex items-center gap-1 text-[11px] text-violet-300"><Edit3 size={13}/>{project.description?'ویرایش':'افزودن'}</button></div><p className="mt-2 text-xs leading-6 text-slate-500">{project.description||'برای این پروژه هنوز توضیحی ثبت نشده است.'}</p></div><p className="mt-2 text-[10px] text-slate-600">۰٪ انتظار · ۵۰٪ در حال انجام · ۱۰۰٪ انجام شده</p></div>}
function RoleBadge({role}:{role:Role}){return <span className={`chip font-semibold ${role==='manager'?'text-amber-300 bg-amber-400/10':'text-sky-300 bg-sky-400/10'}`}>{role==='manager'?'مدیر':'کاربر'}</span>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#11131b] p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold text-white">{title}</h2><button onClick={onClose} className="text-slate-500"><X size={20}/></button></div>{children}</div></div>}
function AccountForm({person,onSubmit}:{person:Person;onSubmit:(n:string,s:string,a:number,r:Role)=>void}){const[n,setN]=useState(person?.name||''),[s,setS]=useState(person?.specialty||''),[a,setA]=useState(String(person?.age||18)),[r,setR]=useState<Role>(person?.role||'user');return <form onSubmit={e=>{e.preventDefault();if(n.trim()&&s.trim()&&Number(a)>0)onSubmit(n.trim(),s.trim(),Number(a),r)}} className="space-y-3"><input className="field" placeholder="نام و نام خانوادگی" value={n} onChange={e=>setN(e.target.value)}/><input className="field" placeholder="تخصص" value={s} onChange={e=>setS(e.target.value)}/><input type="number" min="1" max="120" className="field" placeholder="سن" value={a} onChange={e=>setA(e.target.value)}/><div className="grid grid-cols-2 gap-2">{([['user','کاربر'],['manager','مدیر']] as const).map(([id,label])=><button type="button" key={id} onClick={()=>setR(id)} className={`rounded-xl border p-3 text-right ${r===id?'border-violet-500 bg-violet-500/10':'border-white/10'}`}><b className="text-white">{label}</b></button>)}</div><button className="btn-primary w-full justify-center"><Save size={15}/>ثبت اطلاعات</button></form>}
function DescriptionForm({project,onSubmit}:{project:Project;onSubmit:(d:string)=>void}){const[d,setD]=useState(project?.description||'');return <form onSubmit={e=>{e.preventDefault();onSubmit(d)}} className="space-y-3"><p className="text-xs text-slate-500">توضیحات پروژه «{project?.name}»</p><textarea autoFocus rows={6} className="field resize-none" placeholder="توضیحات پروژه..." value={d} onChange={e=>setD(e.target.value)}/><button className="btn-primary w-full justify-center"><Save size={15}/>ذخیره توضیحات</button></form>}
function GroupForm({onSubmit}:{onSubmit:(n:string)=>void}){const[n,setN]=useState('');return <form onSubmit={e=>{e.preventDefault();onSubmit(n)}} className="space-y-3"><input autoFocus className="field" placeholder="نام گروه" value={n} onChange={e=>setN(e.target.value)}/><button className="btn-primary w-full justify-center">ایجاد گروه</button></form>}
function ProjectForm({groups,onSubmit}:{groups:Group[];onSubmit:(n:string,s:string,e:string,g:string,d:string)=>void}){const[n,setN]=useState(''),[s,setS]=useState('2026-09-01'),[e,setE]=useState('2026-09-30'),[g,setG]=useState(groups[0]?.id||''),[d,setD]=useState('');return <form onSubmit={x=>{x.preventDefault();onSubmit(n,s,e,g,d)}} className="space-y-3"><input autoFocus className="field" placeholder="نام پروژه" value={n} onChange={x=>setN(x.target.value)}/><label className="block text-xs text-slate-500">تاریخ شروع<input type="date" className="field mt-1" value={s} onChange={x=>setS(x.target.value)}/></label><label className="block text-xs text-slate-500">مهلت پایان<input type="date" className="field mt-1" value={e} onChange={x=>setE(x.target.value)}/></label><select className="field" value={g} onChange={x=>setG(x.target.value)}>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><textarea rows={4} className="field resize-none" placeholder="توضیحات اولیه پروژه (اختیاری)" value={d} onChange={x=>setD(x.target.value)}/><button className="btn-primary w-full justify-center">ساخت پروژه</button></form>}
function TaskForm({projects,groups,people,selectedProject,onSubmit}:{projects:Project[];groups:Group[];people:Person[];selectedProject:string;onSubmit:(t:string,p:string,g:string,a:string)=>void}){const[t,setT]=useState(''),[p,setP]=useState(selectedProject||projects[0]?.id||''),[g,setG]=useState(groups[0]?.id||''),[a,setA]=useState(people[0]?.id||'');return <form onSubmit={e=>{e.preventDefault();onSubmit(t,p,g,a)}} className="space-y-3"><input autoFocus className="field" placeholder="عنوان تسک" value={t} onChange={e=>setT(e.target.value)}/><select className="field" value={p} onChange={e=>setP(e.target.value)}>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={g} onChange={e=>setG(e.target.value)}>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={a} onChange={e=>setA(e.target.value)}>{people.map(x=><option key={x.id} value={x.id}>{x.name} — {x.role==='manager'?'مدیر':'کاربر'}</option>)}</select><button className="btn-primary w-full justify-center">ایجاد تسک</button></form>}
function Timeline({projects,progressMap}:{projects:Project[];progressMap:Record<string,number>}){return <section className="rounded-2xl border border-white/10 bg-[#0f1118] p-5"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-bold text-white">تایم‌لاین پروژه‌ها</h2><p className="text-xs text-slate-500 mt-1">تاریخ شروع، مهلت و درصد پیشرفت خودکار</p></div><Clock3 className="text-violet-400"/></div>{projects.map(p=><div key={p.id} className="mb-4 rounded-xl bg-white/[.02] p-4"><div className="flex justify-between"><b className="text-white">{p.name}</b><span className="text-violet-300">{progressMap[p.id]}٪</span></div><p className="text-xs text-slate-500 mt-1">{fmt(p.start)} تا {fmt(p.end)}</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{width:`${progressMap[p.id]}%`}}/></div></div>)}</section>}
function ActivityLog({history,tasks,projects,people}:{history:History[];tasks:Task[];projects:Project[];people:Person[]}){const tm=Object.fromEntries(tasks.map(t=>[t.id,t])),pm=Object.fromEntries(projects.map(p=>[p.id,p])),um=Object.fromEntries(people.map(p=>[p.id,p]));return <section className="rounded-2xl border border-white/10 bg-[#0f1118] p-5"><h2 className="text-xl font-bold text-white">فعالیت افراد</h2><div className="mt-5 space-y-3">{history.length===0?<div className="rounded-xl bg-white/[.03] p-6 text-center text-sm text-slate-500">هنوز فعالیتی ثبت نشده است.</div>:history.map(h=><div key={h.id} className="flex gap-3 rounded-xl border border-white/5 p-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-violet-500/15 text-violet-300"><Check size={16}/></div><div className="text-sm"><b className="text-white">{um[h.personId]?.name}</b> {um[h.personId]&&<RoleBadge role={um[h.personId].role}/>} <span className="text-slate-400">تسک</span> <b className="text-white">{tm[h.taskId]?.title}</b> <span className="text-slate-400">را به</span> <span className="text-violet-300">{h.action}</span><p className="mt-1 text-[10px] text-slate-600">پروژه: {pm[h.projectId]?.name} · {new Date(h.at).toLocaleString('fa-IR')}</p></div></div>)}</div></section>}
