import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Activity, CalendarDays, ChevronLeft, ChevronRight, FolderKanban, GripVertical, LayoutDashboard, Lightbulb, Pencil, Plus, Save, Star, Trash2, UserCircle2, X } from 'lucide-react'

type Status = 'todo' | 'doing' | 'done'
type Role = 'user' | 'manager'
type Person = { id: string; name: string; specialty: string; age: number; role: Role }
type Group = { id: string; name: string }
type Project = { id: string; name: string; start: string; end: string; groupId: string; ownerId: string; description: string; sourceIdeaId?: string }
type Task = { id: string; title: string; description: string; projectId: string; status: Status; groupId: string; assigneeId: string; createdAt: string; startDate: string; dueDate: string }
type History = { id: string; personId: string; action: string; taskId?: string; projectId?: string; at: string; kind: 'task' | 'project' | 'system' }
type Idea = { id: string; title: string; description: string; groupId: string; authorId: string; createdAt: string; ratings: Record<string, number>; promotedProjectId?: string }

const people0: Person[] = [
  { id: 'p1', name: 'احمد سلیمانی', specialty: 'توسعه‌دهنده', age: 29, role: 'manager' },
  { id: 'p2', name: 'محمد رضایی', specialty: 'برنامه‌نویس', age: 27, role: 'user' },
  { id: 'p3', name: 'سارا احمدی', specialty: 'طراح UI/UX', age: 26, role: 'user' },
]
const groups0: Group[] = [{ id: 'g1', name: 'توسعه' }, { id: 'g2', name: 'طراحی' }, { id: 'g3', name: 'بازاریابی' }]
const projects0: Project[] = [
  { id: 'pr1', name: 'وب‌سایت شرکت', start: '2026-09-01', end: '2026-09-24', groupId: 'g1', ownerId: 'p1', description: 'طراحی و توسعه وب‌سایت اصلی شرکت.' },
  { id: 'pr2', name: 'اپلیکیشن موبایل', start: '2026-09-10', end: '2026-10-18', groupId: 'g1', ownerId: 'p2', description: 'نسخه اولیه اپلیکیشن.' },
  { id: 'pr3', name: 'کمپین پاییزه', start: '2026-09-20', end: '2026-10-08', groupId: 'g3', ownerId: 'p3', description: 'برنامه‌ریزی کمپین پاییزه.' },
]
const tasks0: Task[] = [
  { id: 't1', title: 'طراحی صفحه اصلی', description: 'طراحی نسخه اولیه صفحه اصلی وب‌سایت.', projectId: 'pr1', status: 'done', groupId: 'g2', assigneeId: 'p3', createdAt: '2026-09-01', startDate: '2026-09-01', dueDate: '2026-09-05' },
  { id: 't2', title: 'پیاده‌سازی داشبورد', description: 'ساخت داشبورد مدیریت پروژه.', projectId: 'pr1', status: 'doing', groupId: 'g1', assigneeId: 'p1', createdAt: '2026-09-04', startDate: '2026-09-04', dueDate: '2026-09-12' },
  { id: 't3', title: 'اتصال API', description: 'اتصال سرویس‌های مورد نیاز به API.', projectId: 'pr1', status: 'todo', groupId: 'g1', assigneeId: 'p2', createdAt: '2026-09-08', startDate: '2026-09-08', dueDate: '2026-09-16' },
  { id: 't4', title: 'طراحی رابط کاربری', description: 'طراحی صفحات اصلی اپلیکیشن.', projectId: 'pr2', status: 'doing', groupId: 'g2', assigneeId: 'p3', createdAt: '2026-09-10', startDate: '2026-09-10', dueDate: '2026-09-19' },
  { id: 't5', title: 'ساخت نسخه اولیه', description: 'پیاده‌سازی MVP اپلیکیشن.', projectId: 'pr2', status: 'todo', groupId: 'g1', assigneeId: 'p2', createdAt: '2026-09-11', startDate: '2026-09-11', dueDate: '2026-09-25' },
  { id: 't6', title: 'تقویم محتوایی', description: 'تهیه برنامه انتشار محتوای کمپین.', projectId: 'pr3', status: 'todo', groupId: 'g3', assigneeId: 'p3', createdAt: '2026-09-20', startDate: '2026-09-20', dueDate: '2026-09-27' },
]
const meta: Record<Status, { title: string; dot: string; weight: number }> = {
  todo: { title: 'در انتظار انجام', dot: 'bg-slate-400', weight: 0 },
  doing: { title: 'در حال انجام', dot: 'bg-amber-400', weight: 50 },
  done: { title: 'انجام شده', dot: 'bg-emerald-400', weight: 100 },
}
const uid = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
const today = () => new Date().toISOString().slice(0, 10)
const addDays = (s: string, n: number) => { const d = new Date(`${s}T00:00:00`); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10) }
const fmt = (s: string) => new Date(`${s}T00:00:00`).toLocaleDateString('fa-IR', { year: 'numeric', month: '2-digit', day: '2-digit' })
const score = (i: Idea) => { const a = Object.values(i.ratings); return a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0 }
const progress = (id: string, ts: Task[]) => { const a = ts.filter(t => t.projectId === id); return a.length ? Math.round(a.reduce((s, t) => s + meta[t.status].weight, 0) / a.length) : 0 }
const read = <T,>(key: string, fallback: T): T => { try { const x = localStorage.getItem(key); return x ? JSON.parse(x) : fallback } catch { return fallback } }
const jalaliKey = (iso: string) => { const parts = new Intl.DateTimeFormat('fa-IR-u-ca-persian', { year: 'numeric', month: '2-digit' }).formatToParts(new Date(`${iso}T00:00:00`)); const y = parts.find(p => p.type === 'year')?.value || ''; const m = parts.find(p => p.type === 'month')?.value || ''; return `${y}-${m}` }

export default function App() {
  const [page, setPage] = useState<'board' | 'timeline' | 'ideas' | 'activity'>('board')
  const [projects, setProjects] = useState<Project[]>(() => read('orbit-projects', projects0))
  const [tasks, setTasks] = useState<Task[]>(() => read('orbit-tasks', tasks0))
  const [groups] = useState<Group[]>(groups0)
  const [people, setPeople] = useState<Person[]>(() => read('orbit-people', people0))
  const [ideas, setIdeas] = useState<Idea[]>(() => read('orbit-ideas', []))
  const [history, setHistory] = useState<History[]>(() => read('orbit-history', []))
  const [drag, setDrag] = useState<string | null>(null)
  const [userId] = useState(() => localStorage.getItem('orbit-current-user') || 'p1')
  const [modal, setModal] = useState<'idea' | 'project' | 'task' | 'account' | 'projectEdit' | 'taskEdit' | null>(null)
  const [selectedTask, setSelectedTask] = useState<Task | null>(null)
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<{ type: 'task' | 'project'; id: string } | null>(null)
  const [taskPresetDate, setTaskPresetDate] = useState<string | undefined>()
  const [month, setMonth] = useState(() => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1) })
  const current = people.find(p => p.id === userId) || people[0]
  const pg = useMemo(() => Object.fromEntries(projects.map(p => [p.id, progress(p.id, tasks)])), [projects, tasks])
  const pm = useMemo(() => Object.fromEntries(people.map(p => [p.id, p])), [people])
  const gm = useMemo(() => Object.fromEntries(groups.map(g => [g.id, g])), [groups])
  const overall = projects.length ? Math.round(projects.reduce((s, p) => s + pg[p.id], 0) / projects.length) : 0

  useEffect(() => localStorage.setItem('orbit-projects', JSON.stringify(projects)), [projects])
  useEffect(() => localStorage.setItem('orbit-tasks', JSON.stringify(tasks)), [tasks])
  useEffect(() => localStorage.setItem('orbit-ideas', JSON.stringify(ideas)), [ideas])
  useEffect(() => localStorage.setItem('orbit-people', JSON.stringify(people)), [people])
  useEffect(() => localStorage.setItem('orbit-history', JSON.stringify(history)), [history])
  useEffect(() => { setTasks(x => x.map(t => ({ ...t, description: t.description || '' }))) }, [])

  // Prototype mode: roles are informational only. No frontend capability is restricted.
  const log = (action: string, kind: History['kind'], taskId?: string, projectId?: string) => setHistory(x => [{ id: uid('h'), personId: current.id, action, taskId, projectId, at: new Date().toISOString(), kind }, ...x])
  const move = (id: string, status: Status) => { const t = tasks.find(x => x.id === id); if (!t || t.status === status) return; setTasks(x => x.map(a => a.id === id ? { ...a, status } : a)); log(`تغییر وضعیت به «${meta[status].title}»`, 'task', id, t.projectId); setDrag(null) }
  const addIdea = (title: string, description: string, groupId: string) => { if (title.trim()) { setIdeas(x => [{ id: uid('idea'), title: title.trim(), description: description.trim(), groupId, authorId: current.id, createdAt: today(), ratings: {} }, ...x]); log(`ایده «${title.trim()}» ایجاد شد`, 'system') } setModal(null) }
  const rate = (id: string, value: number) => setIdeas(x => x.map(i => i.id === id ? { ...i, ratings: { ...i.ratings, [current.id]: value } } : i))
  const addProject = (name: string, start: string, end: string, groupId: string, description: string) => { if (name.trim() && start && end && end >= start) { const p: Project = { id: uid('pr'), name: name.trim(), start, end, groupId, ownerId: current.id, description: description.trim() }; setProjects(x => [p, ...x]); log(`پروژه «${p.name}» ایجاد شد`, 'project', undefined, p.id) } setModal(null) }
  const updateProject = (id: string, name: string, start: string, end: string, groupId: string, description: string) => { if (name.trim() && start && end && end >= start) { setProjects(x => x.map(p => p.id === id ? { ...p, name: name.trim(), start, end, groupId, description: description.trim() } : p)); log(`پروژه «${name.trim()}» ویرایش شد`, 'project', undefined, id) } setModal(null); setSelectedProject(null) }
  const deleteProject = (id: string) => { const p = projects.find(x => x.id === id); if (!p) return; setProjects(x => x.filter(x => x.id !== id)); setTasks(x => x.filter(t => t.projectId !== id)); log(`پروژه «${p.name}» حذف شد`, 'project', undefined, id); setDeleteTarget(null) }
  const addTask = (title: string, description: string, p: string, g: string, a: string, start: string, due: string) => { if (title.trim() && p && start && due && due >= start) { const t: Task = { id: uid('t'), title: title.trim(), description: description.trim(), projectId: p, status: 'todo', groupId: g, assigneeId: a, createdAt: today(), startDate: start, dueDate: due }; setTasks(x => [...x, t]); log(`تسک «${t.title}» ایجاد شد`, 'task', t.id, p) } setModal(null); setTaskPresetDate(undefined) }
  const updateTask = (id: string, title: string, description: string, p: string, g: string, a: string, start: string, due: string) => { if (title.trim() && p && start && due && due >= start) { setTasks(x => x.map(t => t.id === id ? { ...t, title: title.trim(), description: description.trim(), projectId: p, groupId: g, assigneeId: a, startDate: start, dueDate: due } : t)); log(`تسک «${title.trim()}» ویرایش شد`, 'task', id, p) } setModal(null); setSelectedTask(null) }
  const deleteTask = (id: string) => { const t = tasks.find(x => x.id === id); if (!t) return; setTasks(x => x.filter(x => x.id !== id)); log(`تسک «${t.title}» حذف شد`, 'task', id, t.projectId); setDeleteTarget(null); setSelectedTask(null) }
  const openTask = (date?: string) => { setTaskPresetDate(date); setModal('task') }
  const openTaskEdit = (t: Task) => { setSelectedTask(t); setModal('taskEdit') }
  const openProjectEdit = (p: Project) => { setSelectedProject(p); setModal('projectEdit') }

  // Promote the highest-rated idea from completed Jalali months into a project, once per idea.
  useEffect(() => {
    if (!ideas.length) return
    const currentMonth = jalaliKey(today())
    const candidates = ideas.filter(i => !i.promotedProjectId && jalaliKey(i.createdAt) < currentMonth)
    if (!candidates.length) return
    const groupsByMonth = new Map<string, Idea[]>()
    candidates.forEach(i => { const k = jalaliKey(i.createdAt); groupsByMonth.set(k, [...(groupsByMonth.get(k) || []), i]) })
    const winners = [...groupsByMonth.values()].map(list => list.sort((a, b) => score(b) - score(a))[0])
    if (!winners.length) return
    setProjects(ps => {
      let next = [...ps]
      const ids: Record<string, string> = {}
      winners.forEach(i => { const id = uid('pr'); ids[i.id] = id; next = [{ id, name: i.title, start: today(), end: addDays(today(), 30), groupId: i.groupId, ownerId: i.authorId, description: `پروژه ایجادشده از ایده برتر ماه.\n\n${i.description}`, sourceIdeaId: i.id }, ...next] })
      setIdeas(is => is.map(i => ids[i.id] ? { ...i, promotedProjectId: ids[i.id] } : i))
      winners.forEach(i => log(`ایده برتر «${i.title}» به پروژه تبدیل شد`, 'project', undefined, ids[i.id]))
      return next
    })
  }, [])

  return <div dir="rtl" className="min-h-screen bg-[#08090d] text-slate-200">
    <aside className="fixed right-0 top-0 bottom-0 hidden md:flex w-64 flex-col border-l border-white/10 bg-[#0d0f15] p-5">
      <div className="mb-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 font-black">O</div><div><b className="text-white">Orbit Tasks</b><p className="text-xs text-slate-500">فضای کاری خلاق</p></div></div>
      <nav className="space-y-2">{([['board', 'برد پروژه', LayoutDashboard], ['timeline', 'تقویم', CalendarDays], ['ideas', 'اتاق ایده‌ها', Lightbulb], ['activity', 'فعالیت افراد', Activity]] as const).map(([id, label, Icon]) => <button key={id} onClick={() => setPage(id)} className={`w-full flex gap-3 items-center rounded-xl px-4 py-3 text-sm ${page === id ? 'bg-violet-500/15 text-violet-300' : 'text-slate-400 hover:bg-white/5'}`}><Icon size={18} />{label}</button>)}</nav>
      <div className="mt-auto rounded-2xl border border-white/10 p-4"><p className="text-xs text-slate-500">پیشرفت کل</p><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{ width: `${overall}%` }} /></div><b className="mt-2 block">{overall}٪</b></div>
    </aside>
    <main className="md:mr-64 p-5 md:p-8">
      <header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-violet-400">فضای کاری تیم</p><h1 className="text-3xl font-black text-white">{page === 'ideas' ? 'اتاق ایده‌ها' : page === 'timeline' ? 'تقویم پروژه‌ها' : page === 'activity' ? 'فعالیت افراد' : 'مدیریت پروژه'}</h1></div><div className="flex flex-wrap gap-2"><button onClick={() => setModal('account')} className="btn-secondary"><UserCircle2 size={18} />{current.name}</button>{page !== 'ideas' && <><button onClick={() => openTask()} className="btn-secondary"><Plus size={16} />تسک</button><button onClick={() => setModal('project')} className="btn-primary"><FolderKanban size={16} />پروژه</button></>}</div></header>
      {page === 'ideas' && <Ideas ideas={ideas} people={people} groups={groups} current={current.id} rate={rate} add={() => setModal('idea')} />}
      {page === 'timeline' && <Timeline projects={projects} tasks={tasks} progress={pg} people={people} groups={groups} month={month} setMonth={setMonth} addTask={openTask} />}
      {page === 'activity' && <ActivityLog history={history} tasks={tasks} projects={projects} people={people} />}
      {page === 'board' && <Board projects={projects} tasks={tasks} people={people} groups={groups} progress={pg} drag={drag} setDrag={setDrag} move={move} editTask={openTaskEdit} deleteTask={id => setDeleteTarget({ type: 'task', id })} editProject={openProjectEdit} deleteProject={id => setDeleteTarget({ type: 'project', id })} />}
    </main>
    {modal === 'idea' && <Modal title="ثبت ایده جدید" close={() => setModal(null)}><IdeaForm groups={groups} submit={addIdea} /></Modal>}
    {modal === 'project' && <Modal title="پروژه جدید" close={() => setModal(null)}><ProjectForm groups={groups} submit={addProject} /></Modal>}
    {modal === 'projectEdit' && selectedProject && <Modal title="ویرایش پروژه" close={() => { setModal(null); setSelectedProject(null) }}><ProjectForm groups={groups} initial={selectedProject} submit={(n, s, e, g, d) => updateProject(selectedProject.id, n, s, e, g, d)} /></Modal>}
    {modal === 'task' && <Modal title="تسک جدید" close={() => { setModal(null); setTaskPresetDate(undefined) }}><TaskForm projects={projects} groups={groups} people={people} presetDate={taskPresetDate} submit={addTask} /></Modal>}
    {modal === 'taskEdit' && selectedTask && <Modal title="ویرایش تسک" close={() => { setModal(null); setSelectedTask(null) }}><TaskForm projects={projects} groups={groups} people={people} initial={selectedTask} submit={(t, d, p, g, a, s, due) => updateTask(selectedTask.id, t, d, p, g, a, s, due)} /></Modal>}
    {modal === 'account' && <Modal title="حساب کاربری" close={() => setModal(null)}><AccountForm person={current} submit={(n, s, a, r) => { setPeople(x => x.map(p => p.id === current.id ? { ...p, name: n, specialty: s, age: a, role: r } : p)); log('حساب کاربری ویرایش شد', 'system'); setModal(null) }} /></Modal>}
    {deleteTarget && <Modal title={deleteTarget.type === 'project' ? 'حذف پروژه' : 'حذف تسک'} close={() => setDeleteTarget(null)}><p className="mb-4 text-sm text-slate-400">این عملیات در Prototype محدودیت نقش ندارد و مورد انتخابی حذف خواهد شد.</p><button onClick={() => deleteTarget.type === 'project' ? deleteProject(deleteTarget.id) : deleteTask(deleteTarget.id)} className="w-full rounded-xl bg-red-600 p-3 font-bold">حذف قطعی</button></Modal>}
    <style>{`.btn-primary,.btn-secondary{display:flex;align-items:center;justify-content:center;gap:7px;border-radius:12px;padding:10px 14px;font-size:13px;font-weight:700}.btn-primary{background:#7c3aed;color:white}.btn-secondary{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#cbd5e1}.chip{display:inline-flex;border-radius:999px;background:rgba(255,255,255,.06);padding:4px 8px;font-size:10px;color:#94a3b8}.field{width:100%;border:1px solid rgba(255,255,255,.1);background:#0b0d12;color:#e2e8f0;border-radius:10px;padding:10px;outline:none}.field:focus{border-color:#7c3aed}`}</style>
  </div>
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-[#11131b] p-5"><div className="mb-5 flex justify-between"><h2 className="font-bold text-white">{title}</h2><button onClick={close}><X size={20} /></button></div>{children}</div></div> }

function Board({ projects, tasks, people, groups, progress, drag, setDrag, move, editTask, deleteTask, editProject, deleteProject }: { projects: Project[]; tasks: Task[]; people: Person[]; groups: Group[]; progress: Record<string, number>; drag: string | null; setDrag: (x: string | null) => void; move: (id: string, s: Status) => void; editTask: (t: Task) => void; deleteTask: (id: string) => void; editProject: (p: Project) => void; deleteProject: (id: string) => void }) {
  const pm = Object.fromEntries(projects.map(p => [p.id, p])); const gm = Object.fromEntries(groups.map(g => [g.id, g])); const um = Object.fromEntries(people.map(p => [p.id, p]))
  return <><div className="mb-6 grid grid-cols-2 lg:grid-cols-4 gap-3">{[['پروژه‌ها', projects.length], ['تسک‌ها', tasks.length], ['انجام شده', tasks.filter(t => t.status === 'done').length], ['میانگین پیشرفت', `${projects.length ? Math.round(projects.reduce((s, p) => s + progress[p.id], 0) / projects.length) : 0}٪`]].map(([a, b]) => <div key={a as string} className="rounded-2xl border border-white/10 bg-[#10121a] p-4"><p className="text-xs text-slate-500">{a}</p><b className="mt-2 block text-2xl text-white">{b}</b></div>)}</div>
    <div className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-3">{projects.map(p => <div key={p.id} className="rounded-2xl border border-white/10 bg-[#10121a] p-4"><div className="flex items-center justify-between gap-2"><button onClick={() => editProject(p)} className="font-bold text-white hover:text-violet-300">{p.name}</button><div className="flex gap-1"><button onClick={() => editProject(p)} className="p-1 text-slate-500 hover:text-violet-300"><Pencil size={15} /></button><button onClick={() => deleteProject(p.id)} className="p-1 text-slate-500 hover:text-red-400"><Trash2 size={15} /></button></div></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{ width: `${progress[p.id]}%` }} /></div><p className="mt-2 text-xs text-slate-500">{fmt(p.start)} تا {fmt(p.end)} · {progress[p.id]}٪ · {gm[p.groupId]?.name}</p>{p.description && <p className="mt-2 line-clamp-2 text-xs text-slate-400">{p.description}</p>}</div>)}</div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{(Object.keys(meta) as Status[]).map(status => <section key={status} onDragOver={e => e.preventDefault()} onDrop={() => drag && move(drag, status)} className="min-h-72 rounded-2xl border border-white/10 bg-[#0d0f15] p-4"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${meta[status].dot}`} /><h2 className="font-bold text-white">{meta[status].title}</h2></div><span className="rounded-full bg-white/5 px-2 py-1 text-xs">{tasks.filter(t => t.status === status).length}</span></div><div className="space-y-3">{tasks.filter(t => t.status === status).map(t => <article key={t.id} draggable onDragStart={() => setDrag(t.id)} onDragEnd={() => setDrag(null)} onClick={() => editTask(t)} className="cursor-pointer rounded-xl border border-white/10 bg-[#171a23] p-3 hover:border-violet-500/40"><div className="flex gap-2"><GripVertical size={16} className="mt-1 text-slate-600" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><b className="text-sm text-white">{t.title}</b><button onClick={e => { e.stopPropagation(); deleteTask(t.id) }} className="text-slate-600 hover:text-red-400"><Trash2 size={14} /></button></div>{t.description && <p className="mt-1 line-clamp-2 text-xs text-slate-500">{t.description}</p>}<div className="mt-3 flex flex-wrap gap-1"><span className="chip">{gm[t.groupId]?.name}</span><span className="chip">{um[t.assigneeId]?.name}</span><span className="chip">مهلت: {fmt(t.dueDate)}</span></div><p className="mt-2 text-[10px] text-slate-600">{pm[t.projectId]?.name}</p></div></div></article>)}</div></section>)}</div></>
}

function Ideas({ ideas, people, groups, current, rate, add }: { ideas: Idea[]; people: Person[]; groups: Group[]; current: string; rate: (id: string, v: number) => void; add: () => void }) { const pm = Object.fromEntries(people.map(p => [p.id, p])); const gm = Object.fromEntries(groups.map(g => [g.id, g])); const sorted = [...ideas].sort((a, b) => score(b) - score(a)); return <div><div className="mb-5 flex items-center justify-between"><p className="text-sm text-slate-500">همه اعضای تیم می‌توانند ایده ثبت و به هر ایده از ۱ تا ۵ امتیاز بدهند.</p><button onClick={add} className="btn-primary"><Plus size={16} />ایده جدید</button></div><div className="grid gap-4">{sorted.map((i, idx) => <article key={i.id} className="rounded-2xl border border-white/10 bg-[#10121a] p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="rounded-full bg-violet-500/15 px-2 py-1 text-xs text-violet-300">#{idx + 1}</span><h2 className="font-bold text-white">{i.title}</h2></div><p className="mt-2 text-sm leading-7 text-slate-400">{i.description || 'بدون توضیحات'}</p><div className="mt-3 flex flex-wrap gap-2"><span className="chip">گروه: {gm[i.groupId]?.name}</span><span className="chip">نویسنده: {pm[i.authorId]?.name}</span><span className="chip">میانگین: {score(i).toFixed(1)} / 5</span>{i.promotedProjectId && <span className="chip">به پروژه تبدیل شده</span>}</div></div><div className="shrink-0 text-center"><div className="text-2xl font-black text-white">{score(i).toFixed(1)}</div><div className="text-[10px] text-slate-500">امتیاز</div></div></div><div className="mt-4 flex flex-wrap gap-1">{[1, 2, 3, 4, 5].map(v => <button key={v} onClick={() => rate(i.id, v)} className={`rounded-lg p-2 ${i.ratings[current] === v ? 'bg-violet-500 text-white' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}><Star size={15} fill="currentColor" /></button>)}</div></article>)}{!ideas.length && <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-500">هنوز ایده‌ای ثبت نشده است.</div>}</div></div> }

function Timeline({ projects, tasks, progress, people, groups, month, setMonth, addTask }: { projects: Project[]; tasks: Task[]; progress: Record<string, number>; people: Person[]; groups: Group[]; month: Date; setMonth: (d: Date) => void; addTask: (date?: string) => void }) { const year = month.getFullYear(); const mon = month.getMonth(); const first = new Date(year, mon, 1); const days = new Date(year, mon + 1, 0).getDate(); const start = first.getDay(); const cells = Array.from({ length: start + days }, (_, i) => i < start ? null : i - start + 1); const tasksFor = (day: number) => { const d = `${year}-${String(mon + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; return tasks.filter(t => t.startDate <= d && d <= t.dueDate) }; return <div><div className="mb-4 flex items-center justify-between"><button onClick={() => setMonth(new Date(year, mon - 1, 1))} className="btn-secondary"><ChevronRight size={16} /></button><h2 className="font-bold text-white">{month.toLocaleDateString('fa-IR', { year: 'numeric', month: 'long' })}</h2><button onClick={() => setMonth(new Date(year, mon + 1, 1))} className="btn-secondary"><ChevronLeft size={16} /></button></div><div className="grid grid-cols-7 gap-2 text-center text-xs text-slate-500 mb-2">{['شنبه', 'یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنجشنبه', 'جمعه'].map(x => <div key={x}>{x}</div>)}</div><div className="grid grid-cols-7 gap-2">{cells.map((day, idx) => day === null ? <div key={idx} className="min-h-28 rounded-xl bg-transparent" /> : <div key={idx} className="min-h-28 rounded-xl border border-white/10 bg-[#10121a] p-2 text-right"><div className="mb-2 flex items-center justify-between"><b className="text-sm text-white">{day}</b><button onClick={() => addTask(`${year}-${String(mon + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`)} className="rounded-md bg-violet-500/15 p-1 text-violet-300"><Plus size={13} /></button></div><div className="space-y-1">{tasksFor(day).slice(0, 3).map(t => <button key={t.id} onClick={() => addTask(`${year}-${String(mon + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`)} className="block w-full truncate rounded bg-white/5 px-2 py-1 text-right text-[10px] text-slate-300">{t.title}</button>)}{projects.filter(p => { const d = `${year}-${String(mon + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; return p.start <= d && d <= p.end }).slice(0, 2).map(p => <div key={p.id} className="truncate rounded bg-violet-500/10 px-2 py-1 text-[10px] text-violet-300">پروژه: {p.name} · {progress[p.id]}٪</div>)}</div></div>)}</div></div> }

function ActivityLog({ history, tasks, projects, people }: { history: History[]; tasks: Task[]; projects: Project[]; people: Person[] }) { const pm = Object.fromEntries(people.map(p => [p.id, p])); const tm = Object.fromEntries(tasks.map(t => [t.id, t])); const prm = Object.fromEntries(projects.map(p => [p.id, p])); return <div className="space-y-3">{history.length ? history.map(h => <div key={h.id} className="rounded-xl border border-white/10 bg-[#10121a] p-4"><div className="flex items-start gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-violet-500/15 text-violet-300"><Activity size={16} /></div><div><b className="text-sm text-white">{pm[h.personId]?.name || 'کاربر'}</b><p className="mt-1 text-sm text-slate-400">{h.action}{h.taskId && tm[h.taskId] ? ` · ${tm[h.taskId].title}` : ''}{h.projectId && prm[h.projectId] ? ` · ${prm[h.projectId].name}` : ''}</p><time className="mt-1 block text-[10px] text-slate-600">{new Date(h.at).toLocaleString('fa-IR')}</time></div></div></div>) : <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-500">هنوز فعالیتی ثبت نشده است.</div>}</div> }

function IdeaForm({ groups, submit }: { groups: Group[]; submit: (t: string, d: string, g: string) => void }) { const [t, setT] = useState(''), [d, setD] = useState(''), [g, setG] = useState(groups[0]?.id || ''); return <form onSubmit={e => { e.preventDefault(); submit(t, d, g) }} className="space-y-3"><input autoFocus className="field" placeholder="عنوان ایده" value={t} onChange={e => setT(e.target.value)} /><textarea className="field resize-none" rows={6} placeholder="ایده خود را توضیح دهید..." value={d} onChange={e => setD(e.target.value)} /><select className="field" value={g} onChange={e => setG(e.target.value)}>{groups.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn-primary w-full">ثبت ایده</button></form> }
function ProjectForm({ groups, submit, initial }: { groups: Group[]; submit: (n: string, s: string, e: string, g: string, d: string) => void; initial?: Project }) { const [n, setN] = useState(initial?.name || ''), [s, setS] = useState(initial?.start || today()), [e, setE] = useState(initial?.end || addDays(today(), 30)), [g, setG] = useState(initial?.groupId || groups[0]?.id || ''), [d, setD] = useState(initial?.description || ''); return <form onSubmit={x => { x.preventDefault(); submit(n, s, e, g, d) }} className="space-y-3"><input className="field" placeholder="نام پروژه" value={n} onChange={x => setN(x.target.value)} /><label className="block text-xs text-slate-500">تاریخ شروع<input type="date" className="field mt-1" value={s} onChange={x => setS(x.target.value)} /></label><label className="block text-xs text-slate-500">تاریخ پایان<input type="date" className="field mt-1" min={s} value={e} onChange={x => setE(x.target.value)} /></label><select className="field" value={g} onChange={x => setG(x.target.value)}>{groups.map(q => <option key={q.id} value={q.id}>{q.name}</option>)}</select><textarea className="field" rows={5} placeholder="توضیحات پروژه" value={d} onChange={x => setD(x.target.value)} /><button className="btn-primary w-full"><Save size={16} />{initial ? 'ذخیره تغییرات' : 'ساخت پروژه'}</button></form> }
function TaskForm({ projects, groups, people, presetDate, submit, initial }: { projects: Project[]; groups: Group[]; people: Person[]; presetDate?: string; submit: (t: string, d: string, p: string, g: string, a: string, s: string, due: string) => void; initial?: Task }) { const [t, setT] = useState(initial?.title || ''), [desc, setDesc] = useState(initial?.description || ''), [p, setP] = useState(initial?.projectId || projects[0]?.id || ''), [g, setG] = useState(initial?.groupId || groups[0]?.id || ''), [a, setA] = useState(initial?.assigneeId || people[0]?.id || ''), [s, setS] = useState(initial?.startDate || presetDate || today()), [d, setD] = useState(initial?.dueDate || addDays(presetDate || today(), 3)); useEffect(() => { if (presetDate && !initial) { setS(presetDate); setD(addDays(presetDate, 3)) } }, [presetDate, initial]); return <form onSubmit={e => { e.preventDefault(); submit(t, desc, p, g, a, s, d) }} className="space-y-3"><input autoFocus className="field" placeholder="عنوان تسک" value={t} onChange={e => setT(e.target.value)} /><textarea className="field resize-none" rows={4} placeholder="توضیحات تسک" value={desc} onChange={e => setDesc(e.target.value)} /><select className="field" value={p} onChange={e => setP(e.target.value)}>{projects.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={g} onChange={e => setG(e.target.value)}>{groups.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={a} onChange={e => setA(e.target.value)}>{people.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><label className="block text-xs text-slate-500">شروع تسک<input type="date" className="field mt-1" value={s} onChange={e => setS(e.target.value)} /></label><label className="block text-xs text-slate-500">مهلت نهایی تسک<input type="date" className="field mt-1" min={s} value={d} onChange={e => setD(e.target.value)} /></label><p className="text-xs text-amber-300">بازه زمانی و مهلت تسک در تقویم نمایش داده می‌شود.</p><button className="btn-primary w-full"><Save size={16} />{initial ? 'ذخیره تغییرات' : 'ساخت تسک'}</button></form> }
function AccountForm({ person, submit }: { person: Person; submit: (n: string, s: string, a: number, r: Role) => void }) { const [n, setN] = useState(person.name), [s, setS] = useState(person.specialty), [a, setA] = useState(String(person.age)), [r, setR] = useState<Role>(person.role); return <form onSubmit={e => { e.preventDefault(); submit(n, s, +a, r) }} className="space-y-3"><input className="field" value={n} onChange={e => setN(e.target.value)} /><input className="field" value={s} onChange={e => setS(e.target.value)} /><input className="field" type="number" value={a} onChange={e => setA(e.target.value)} /><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-amber-300">در نسخه Prototype نقش فقط اطلاعاتی است و هیچ قابلیتی را محدود نمی‌کند.</div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setR('user')} className={`btn-secondary ${r === 'user' ? 'border-violet-500 text-violet-300' : ''}`}>کاربر</button><button type="button" onClick={() => setR('manager')} className={`btn-secondary ${r === 'manager' ? 'border-violet-500 text-violet-300' : ''}`}>مدیر</button></div><button className="btn-primary w-full"><Save size={16} />ذخیره</button></form> }
